# Generated by Django 4.2.4 on 2023-08-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('group_size', models.CharField(max_length=1)),
                ('major', models.CharField(max_length=100)),
                ('mbti', models.CharField(max_length=4)),
                ('army', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('body', models.CharField(max_length=20)),
                ('eyes', models.CharField(max_length=20)),
                ('face', models.CharField(max_length=20)),
                ('hobby', models.CharField(max_length=100)),
                ('self_intro', models.TextField()),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
