# Generated by Django 4.2.3 on 2023-08-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='peoplenum',
            field=models.IntegerField(),
        ),
    ]
