# Generated by Django 4.2.3 on 2023-08-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_info_peoplenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='peoplenum',
            new_name='groups',
        ),
    ]
