# Generated by Django 4.2.3 on 2023-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_peoplenum_info_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='groups',
            field=models.CharField(max_length=10),
        ),
    ]
