# Generated by Django 4.2.3 on 2023-08-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_info_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='groups',
            new_name='peoplenums',
        ),
        migrations.AddField(
            model_name='info',
            name='ages',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='info',
            name='jobs',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='info',
            name='locations',
            field=models.CharField(default='', max_length=10),
        ),
    ]
