# Generated by Django 4.2.3 on 2023-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_groups_info_peoplenums_info_ages_info_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='peoplenums',
            field=models.CharField(default='', max_length=10),
        ),
    ]
